# Generated by Django 2.0.2 on 2018-03-11 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('is_variation', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=100)),
                ('brand_id', models.IntegerField()),
                ('code', models.IntegerField()),
                ('family', models.IntegerField()),
                ('is_complement', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_visibility', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('price_offer', models.FloatField()),
                ('offer_day_from', models.DateTimeField()),
                ('offer_day_to', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('sku', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Product')),
            ],
        ),
    ]
