# Generated by Django 2.0.2 on 2018-03-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_complement',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_variation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='is_visibility',
            field=models.BooleanField(default=True),
        ),
    ]
